In [ ]:
#Numpy (numerical python) is a scientific computing package that 
#provides numerous ways to craete and operate  on arrays of numbers. 
#The opertaions can be grouped into four (Creating array, manipulating 
#arrays,combining arrats and linear algebra with arrays)

In [2]:
import numpy as np

In [9]:
#CREATING ARRAYS
#1. Random integers in a specific range
np.random.randint(7,size=7)

array([0, 0, 1, 0, 5, 5, 4])

In [13]:
# to craete a 3x2 array of integers between 5 and 10
np.random.randint(5, 10, size=(3,2))

array([[5, 5],
       [5, 6],
       [6, 6]])

In [14]:
#2.Random floats between 0 and 1 (a 1 dimension array of floats between 0 and 1. it is useful to craete random noise data)
np.random.random(6)

array([0.57486301, 0.8667275 , 0.22562028, 0.53359054, 0.34353511,
       0.23542409])

In [16]:
#3. Sample from a standard normal distribution (used to create a sample from a 
#standard normal distribution (i.e zero mean and unit variance))
print(np.random.randn(200).mean())
print(np.random.randn(200).std())

-0.030526213208104794
1.053753314392725


In [31]:
#4. Matrix with ones and zeros (a matrix can be considered as a 2-dimensional array. 
#It can be craeted withzeros or ones with np.zeros and np.ones, respectively)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [33]:
#5. Identity matrix (an identity matrix is a square matrix (nxn) that has ones 
#on the diagonal and zeros on every other position, np.eye or np.identity can be used to create one.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
#6. Arange (arange function is used to create arrays with evenly spaced sequential values in a 
#specified interval. we can specify start value, stop value and step size)
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
#the default start value is zero and the default step size is one
np.arange(0,10,4)

array([0, 4, 8])

In [42]:
np.arange(20,100,5)

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [44]:
#7. Array with only one value(we can create an array that has the same value at every position using np.full)
np.full((5,4),8)


array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [50]:
np.full((5,4),8, dtype="float")

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [54]:
#MANIPULATING ARRAYS
#lets create a 2 dimensional array:
A=np.random.randint(7, size=(5,8))
A

array([[6, 3, 1, 4, 1, 6, 4, 0],
       [3, 3, 3, 3, 6, 4, 0, 2],
       [2, 5, 6, 1, 1, 6, 0, 0],
       [0, 6, 1, 1, 0, 4, 6, 3],
       [2, 5, 6, 2, 4, 1, 2, 1]])

In [55]:
#8. Ravel(this functions flattens the array i.e converts to a 1 dimension array)
A.ravel()

array([6, 3, 1, 4, 1, 6, 4, 0, 3, 3, 3, 3, 6, 4, 0, 2, 2, 5, 6, 1, 1, 6,
       0, 0, 0, 6, 1, 1, 0, 4, 6, 3, 2, 5, 6, 2, 4, 1, 2, 1])

In [56]:
#an array is flattened by adding row after row. it can be changed to column wise by 
#setting the order parameters as F (Fortran-style)
A.ravel(order="F")

array([6, 3, 2, 0, 2, 3, 3, 5, 6, 5, 1, 3, 6, 1, 6, 4, 3, 1, 1, 2, 1, 6,
       1, 0, 4, 6, 4, 6, 4, 1, 4, 0, 0, 6, 2, 0, 2, 0, 3, 1])

In [57]:
#9. Reshape(it reshapes an array. the shape of A is (5,8 and the size is 40))
A.shape

(5, 8)

In [58]:
A.size

40

In [59]:
A.reshape(5,8)

array([[6, 3, 1, 4, 1, 6, 4, 0],
       [3, 3, 3, 3, 6, 4, 0, 2],
       [2, 5, 6, 1, 1, 6, 0, 0],
       [0, 6, 1, 1, 0, 4, 6, 3],
       [2, 5, 6, 2, 4, 1, 2, 1]])

In [60]:
A.reshape(8,5)

array([[6, 3, 1, 4, 1],
       [6, 4, 0, 3, 3],
       [3, 3, 6, 4, 0],
       [2, 2, 5, 6, 1],
       [1, 6, 0, 0, 0],
       [6, 1, 1, 0, 4],
       [6, 3, 2, 5, 6],
       [2, 4, 1, 2, 1]])

In [62]:
#Numpy can figure out a dimension by passing -1
A.reshape(1,-1)

array([[6, 3, 1, 4, 1, 6, 4, 0, 3, 3, 3, 3, 6, 4, 0, 2, 2, 5, 6, 1, 1, 6,
        0, 0, 0, 6, 1, 1, 0, 4, 6, 3, 2, 5, 6, 2, 4, 1, 2, 1]])

In [63]:
#9. Transpose (transposing a matrix is to switch rows and columns)
A

array([[6, 3, 1, 4, 1, 6, 4, 0],
       [3, 3, 3, 3, 6, 4, 0, 2],
       [2, 5, 6, 1, 1, 6, 0, 0],
       [0, 6, 1, 1, 0, 4, 6, 3],
       [2, 5, 6, 2, 4, 1, 2, 1]])

In [67]:
A.reshape(-1,5)

array([[0, 4, 3, 0, 0],
       [4, 3, 1, 0, 3],
       [3, 1, 2, 3, 3],
       [4, 4, 4, 1, 0],
       [3, 0, 1, 0, 2],
       [0, 3, 2, 4, 1],
       [3, 2, 1, 0, 0],
       [0, 2, 2, 2, 4]])

In [65]:
#10.transpose
A.transpose()

array([[6, 3, 2, 0, 2],
       [3, 3, 5, 6, 5],
       [1, 3, 6, 1, 6],
       [4, 3, 1, 1, 2],
       [1, 6, 1, 0, 4],
       [6, 4, 6, 4, 1],
       [4, 0, 0, 6, 2],
       [0, 2, 0, 3, 1]])

In [77]:
#11. Vsplit (splits an array into multiple sub-arrays vertically)
A = np.random.randint(5, size=(4,3))
np.vsplit(A, 2)

[array([[1, 1, 4],
        [4, 4, 4]]),
 array([[1, 2, 3],
        [2, 1, 2]])]

In [78]:
#we split (a 4x3 array into 2 sub-arrays with a shape of 2x3. A particular sub-array is accessible after splitting.)
A = np.random.randint(5, size=(6,3))
np.vsplit(A,3)[0]
#we splited a 6x3 array into 3 sub-arrays and get the first one

array([[2, 3, 3],
       [3, 3, 4]])

In [80]:
#12. Hsplit (It is similar to vslip but works horizontal).
a= np.array([[1,1,2,2,3,3,4,4,]])
np.hsplit(a,2)

[array([[1, 1, 2, 2]]), array([[3, 3, 4, 4]])]

In [81]:
#if it is applied on a 6x3 arrays to get 3 sub-arrays, resulting arrays will have a shape of(6,1)
A=np.random.randint(5, size=(6,3))
np.hsplit(A, 3)[0]

array([[0],
       [2],
       [4],
       [4],
       [1],
       [3]])

In [82]:
np.hsplit(A, 3)[0].shape

(6, 1)

In [85]:
#COMBINING ARRAYS (#we may need to combine arrays in some cases. 
#Numpy provides functions and methods to combine array in many different ways.
#13. Concatenate: it is similar to the concat function of pandas
a=np.array([1,2,3,4])
b=np.array([3,3,3])
np.concatenate((a,b))

array([1, 2, 3, 4, 3, 3, 3])

In [90]:
#these arrays can be converted to column vectors using the reshape function and then concatenate vertically.
a=np.array([1,2,3,4])
b=np.array([3,3,3,3])

np.concatenate((a.reshape(-1,1),b.reshape(-1,1)), axis=1)

array([[1, 3],
       [2, 3],
       [3, 3],
       [4, 3]])

In [91]:
#14.Vstack: this is used to stack arrays vertically (rows on top of each other)
a= np.array([1,2,3,4])
b=np.array([4,4,4,4])
c= np.array([8,8,8,8])

np.vstack((a,b,c))

array([[1, 2, 3, 4],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [93]:
#it also works with higher dimensional arrays
X= np.random.randint(5, size=(3,3,3))
Y= np.random.randint(5, size=(3,3,3))
Z=np.random.randint(5, size=(3,3,3))

np.vstack((X,Y,Z))

array([[[3, 3, 3],
        [4, 4, 3],
        [4, 2, 3]],

       [[1, 3, 4],
        [4, 1, 3],
        [2, 2, 0]],

       [[0, 4, 2],
        [0, 3, 0],
        [3, 2, 4]],

       [[3, 0, 2],
        [4, 2, 4],
        [2, 1, 2]],

       [[4, 0, 1],
        [4, 1, 2],
        [3, 1, 0]],

       [[0, 4, 3],
        [2, 4, 0],
        [4, 2, 1]],

       [[3, 1, 0],
        [4, 0, 3],
        [1, 1, 2]],

       [[4, 2, 0],
        [1, 3, 2],
        [3, 3, 4]],

       [[2, 0, 1],
        [2, 0, 4],
        [0, 0, 3]]])

In [96]:
#15. Hstack: similar to vstack but works horizontally
X= np.array([1,2,3,4]).reshape(-1,1)
Y= np.array([3,3,3,3]).reshape(-1,1)
Z= np.array([0,1,4,6,]).reshape(-1,1)

np.hstack((X,Y,Z))

array([[1, 3, 0],
       [2, 3, 1],
       [3, 3, 4],
       [4, 3, 6]])

In [103]:
#LINEAR ALGEBRA WITH NUMPY ARRAYS 
#16. Det: returns the determinant of a matrix
A=np.random.randint(5, size=(3,3))
A

array([[3, 1, 1],
       [3, 2, 0],
       [0, 1, 1]])

In [104]:
np.linalg.det(A)

6.0

In [105]:
#17. Inv: calculates the inverse of a matrix
np.linalg.inv(A)

array([[ 0.33333333,  0.        , -0.33333333],
       [-0.5       ,  0.5       ,  0.5       ],
       [ 0.5       , -0.5       ,  0.5       ]])

In [106]:
#18. Eig: computes the eigenvalues and right eigenvectors for a square matrix.
np.linalg.eig(A)

(array([4.52510225+0.j       , 0.73744887+0.8843676j,
        0.73744887-0.8843676j]),
 array([[ 0.62930403+0.j        , -0.10425715-0.31205089j,
         -0.10425715+0.31205089j],
        [ 0.74765768+0.j        , -0.18223374+0.61382945j,
         -0.18223374-0.61382945j],
        [ 0.21209532+0.j        ,  0.69408858+0.j        ,
          0.69408858-0.j        ]]))

In [107]:
#19. Dot: calculates the dot product of two vectors which is the sum of the products of 
#elements with regards to their position. the fisrt element of the fist vector is multiplied by the first
#element of the second vector and so on
a=np.array([1,2,3,4])
b= np.array([2,2,2,2])
np.dot(a,b)

20

In [108]:
#Matmul: it performs matrix multiplication
A=([[1,2],[3,4]])
B=([[3,4],[3,1]])
np.matmul(A,B)

array([[ 9,  6],
       [21, 16]])