In [1]:
import numpy as np

In [2]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
#using range (1,101) make a list of all odd numbers
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [7]:
#using range(1,101) make a list of all even numbers
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
#print all elements of a list using for loop
r = [9, 8, 7, 6, 5, 4, 3, 2, 1]
#to print the list using for loop
for t in range(len(r)):
    print (r[t]),

9
8
7
6
5
4
3
2
1


In [15]:
#write a python script to merge two python dictionaries
w = {"demola":10, "irekanmi":5,"ade":1}
y = {"eyilayomi":8, "desire":7, "eyilore":4}
z=w.copy()
z.update(y)
print(z)

{'demola': 10, 'irekanmi': 5, 'ade': 1, 'eyilayomi': 8, 'desire': 7, 'eyilore': 4}


In [16]:
#write a python program to remove key from a dictionary
w = {"demola":10, "irekanmi":5,"ade":1,"ayo":30}
print(w)
if "ayo" in w:
    del w["ayo"]
print(w)

{'demola': 10, 'irekanmi': 5, 'ade': 1, 'ayo': 30}
{'demola': 10, 'irekanmi': 5, 'ade': 1}


In [22]:
#write a python program to remove key from a dictionary
def max_num_in_k (k):
    max = k[0]
    for a in k:
        if a > max:
            max = a
    return max
print (max_num_in_k ([-9, -8, 7, -6, 5, -4, 3, 2, 1]))

7


In [23]:
#Take input of age of 3 people by user and determine youngest among them
def min_num_in_age(age):
    min = age[0]
    for b in age:
        if b < min:
            min = b
    return min 
print(min_num_in_age([35, 21,40]))

21


In [26]:
#Take input of age of 3 people by user and determine oldest among them
def max_num_in_age(age):
    max = age[0]
    for d in age:
        if d > max:
            max = d
    return max 
print(max_num_in_age([35, 21,40]))

40


In [ ]:
#A company decided to give bonus to of 5% to employee if his/her year of service is more than 5 years. 
#Ask user for their salary and year of service and print the net bonus amount.

a = int(input("salary"))
b = int(input("year of service"))
c = 0.05 * a
if (b >= 5):
    print(c)
else:
    print(a)

In [ ]:
#A school has following rules for grading systems.
maths=int(input"marks of maths"))
eng=int(input"marks of eng"))
science = int(input"marks of science"))
art = int(input"marks of art"))
phonics = int(input"marks of phonics"))
avg=(maths+eng+science+art+phonics)/5
if(avg>=80):
    print("Grade A")
elif("avg>=60&avg<80"):
    print("Grade B")
elif("avg>=50&avg<60"):
    print("Grade C")
elif("avg>=45&avg<50"):
    print("Grade D")
elif("avg>=40&avg<45"):
    print("Grade E")
else:
    print("Grade F")    